name: Deploy TailwindCSS Site

on:
  push:
    branches:
      - main  # Change this if your branch name is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use the version you prefer

      - name: Install Dependencies
        run: npm install

      - name: Build TailwindCSS
        run: npm run build  # Ensure your package.json has a "build" script

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch where the built files will be stored
          folder: dist  # Change to the correct build output folder
